spring:
  datasource:
    url: jdbc:mariadb://localhost:8888/product-manager
    username: root
    password: 12345
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
